### ISSUE TITLE
Elaborar nome das funções

### ISSUE THREAD

**Issue by Heictor** [eguatech/matlab#1]
javaS1.js
- increment()

- rand(n1,n2,e)

- round(x, z)

- array()

- rw(n,ex)

- seq(a, b)

- count(a, b)

- ticker()

- time(w)

- crypto(t)

- plot(z)

- clear()

- save(x)

- load()

javaS2.js

- matrix(z)

- matrixMult(a, b)

- matrixInv(m)

- matrixId(n)

- max(a)

- min(a)

- range(a)

**Comment by lucaspompeun** [comment]
@Heictor não esquece de dar um "assignees" e marcar quem deve executar a tarefa, pra aparecer notificações e todo mundo ficar ciente. Também atribui um projeto, que é sempre o dev-team, só rpa ter um controle de todas as issues num lugar só, que é o trello do github, e não precisar ficar olhando repositório por repositório.

**Comment by Heictor** [comment]
Tô vendo anime.

**Comment by lucaspompeun** [comment]
@JulioAzancort @Heictor @BrennusCaio sugiro quebrar essa issue em diversas issues para solução mais rápida. issue aberta há 1 semana não é bom

**Comment by JulioAzancort** [comment]
Vou verificar com o Heictor se ele já fez de alguma e já faço hoje pela noite.

**Comment by Heictor** [comment]
Os nomes foram alterados:
    "1) Function ajuda() 
    "2) Function exemplo() 
    "3) Function rand(n1,n2,e) 
    "4) Function aprox(x,z) 
    "5) Function matrizn(z)
    "6) Function pale(n)
    "7) Function vet(a,b) 
    "8) Function qtd(a,b) 
    "12) Function plot(z) 
    "13) Function limpar() 
    "14) Function salvar(x) 
    "15) Function carregar() 
    "16) Function matriz(z) 
    "17) Function matrizmult(a,b)
    "18) Function matrizinv(m) 
    "19) Function matrizid(n) 
    "20) Function max(a) 
    "21) Function min(a) 
    "22) Function intervalo(a) 
    "23) Function mediana(a)
    "24) Function smtr(a)
    "25) Function ve(a) 
    "26) Function sqr(array)
    "27) Function variancia(array, flag) 
    "28) Function devpad(array, flag) 
    "29) Function covar(array1, array2) 
    "30) Function coefvar(array) 
    "31) Function coefcorr(array1, array2) 
    "32) Function coluna(a,c) 
    "33) Function linha(a,r)
    "34) Function transposta(a)
